# -*- coding: utf-8 -*-
"""
导入节点重要性数据到数据库

功能：
1. 读取节点重要性分数文件
2. 将数据转换为适合数据库的格式
3. 插入到 sqe_node_importance 表中
"""

import os
import sys
import csv
import json
from pathlib import Path
from sqlalchemy import text

# 添加项目根目录到 Python 路径
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from src.db import get_engine

def import_node_importance():
    """
    导入节点重要性数据到数据库
    """
    engine = get_engine()
    
    # 数据文件路径
    data_file = os.path.join(str(Path(__file__).resolve().parents[2]), "data", "flavor", "node_importance_scores.csv")
    
    if not os.path.exists(data_file):
        print(f"数据文件不存在: {data_file}")
        return
    
    # 开始事务
    with engine.begin() as conn:
        total_rows = 0
        success_rows = 0
        
        with open(data_file, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            
            for row in reader:
                total_rows += 1
                
                try:
                    # 构建数据字典
                    node_data = {
                        'snapshot_id': 's0',
                        'recipe_id': int(row['recipe_id']),
                        'model_version': 'phaseC_v1',
                        'embedding_version': 'emb_v2',
                        'param_version': 'phaseB_v3',
                        'canonical_id': int(row['ingredient_id']),  # 假设ingredient_id就是canonical_id
                        'ingredient_name': row['ingredient_name'],
                        'role': None,  # 需要从数据库获取
                        'amount_value': None,  # 需要从数据库获取
                        'amount_unit': None,  # 需要从数据库获取
                        'order_no': None,  # 需要从数据库获取
                        'base_score': 0.0,  # 基础分数，这里设为0
                        'learned_contribution': float(row['importance_score']),
                        'normalized_contribution': None,  # 需要计算
                        'contribution_ratio': None,  # 需要计算
                        'residual_effect': None,  # 残差效果
                        'attention_weight': None,  # 注意力权重
                        'degree_value': None,  # 节点度
                        'neighbor_count': None,  # 邻居数量
                        'synergy_contrib': None,  # 协同贡献
                        'conflict_contrib': None,  # 冲突贡献
                        'balance_contrib': None,  # 平衡贡献
                        'rank_no': int(row['rank']),
                        'is_key_node': 1 if int(row['rank']) <= 3 else 0,  # 前3名为关键节点
                        'threshold_flag': 1 if float(row['importance_score']) > 0.05 else 0,  # 阈值标记
                        'node_embedding_json': None,  # 节点嵌入
                        'explanation': json.dumps({'summary': f'节点重要性分数: {row["importance_score"]}'}),
                        'note': 'Generated by phaseC node importance analysis'
                    }
                    
                    # 从数据库获取原料的角色、用量等信息
                    ingredient_info_sql = text("""
                    SELECT role, amount, unit, line_no 
                    FROM recipe_ingredient 
                    WHERE recipe_id = :recipe_id AND ingredient_id = :ingredient_id
                    """)
                    
                    result = conn.execute(ingredient_info_sql, {
                        'recipe_id': node_data['recipe_id'],
                        'ingredient_id': node_data['canonical_id']
                    })
                    
                    ingredient_info = result.fetchone()
                    if ingredient_info:
                        node_data['role'] = ingredient_info[0]
                        node_data['amount_value'] = ingredient_info[1]
                        node_data['amount_unit'] = ingredient_info[2]
                        node_data['order_no'] = ingredient_info[3]
                    
                    # 计算标准化贡献和贡献比例
                    # 这里简单处理，实际应该基于每个配方的总重要性计算
                    # 先插入，后续可以通过SQL更新
                    
                    # 插入数据
                    insert_sql = text("""
                    INSERT INTO sqe_node_importance (
                        snapshot_id, recipe_id, model_version, embedding_version, param_version,
                        canonical_id, ingredient_name, role, amount_value, amount_unit,
                        order_no, base_score, learned_contribution, normalized_contribution,
                        contribution_ratio, residual_effect, attention_weight, degree_value,
                        neighbor_count, synergy_contrib, conflict_contrib, balance_contrib,
                        rank_no, is_key_node, threshold_flag, node_embedding_json,
                        explanation, note
                    ) VALUES (
                        :snapshot_id, :recipe_id, :model_version, :embedding_version, :param_version,
                        :canonical_id, :ingredient_name, :role, :amount_value, :amount_unit,
                        :order_no, :base_score, :learned_contribution, :normalized_contribution,
                        :contribution_ratio, :residual_effect, :attention_weight, :degree_value,
                        :neighbor_count, :synergy_contrib, :conflict_contrib, :balance_contrib,
                        :rank_no, :is_key_node, :threshold_flag, :node_embedding_json,
                        :explanation, :note
                    )
                    ON DUPLICATE KEY UPDATE
                        learned_contribution = :learned_contribution,
                        rank_no = :rank_no,
                        is_key_node = :is_key_node,
                        threshold_flag = :threshold_flag
                    """)
                    
                    conn.execute(insert_sql, node_data)
                    success_rows += 1
                    
                    if total_rows % 100 == 0:
                        print(f"处理进度: {total_rows} 行, 成功: {success_rows} 行")
                        
                except Exception as e:
                    print(f"处理行失败: recipe_id={row['recipe_id']}, ingredient_id={row['ingredient_id']}, 错误: {e}")
                    continue
        
        # 更新标准化贡献和贡献比例
        print("更新标准化贡献和贡献比例...")
        update_sql = text("""
        UPDATE sqe_node_importance sni
        JOIN (
            SELECT recipe_id, SUM(learned_contribution) as total_contribution
            FROM sqe_node_importance
            WHERE snapshot_id = 's0' AND model_version = 'phaseC_v1'
            GROUP BY recipe_id
        ) t ON sni.recipe_id = t.recipe_id
        SET 
            sni.normalized_contribution = sni.learned_contribution / t.total_contribution,
            sni.contribution_ratio = sni.learned_contribution / t.total_contribution
        WHERE sni.snapshot_id = 's0' AND sni.model_version = 'phaseC_v1'
        """)
        
        conn.execute(update_sql)
        
        print(f"导入完成: 总计 {total_rows} 行, 成功 {success_rows} 行")

if __name__ == "__main__":
    print("开始导入节点重要性数据...")
    import_node_importance()
    print("节点重要性数据导入完成！")
