# Generated by Django 5.2 on 2026-04-01 14:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                ("entity_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("label", models.CharField(max_length=50)),
                ("normalized_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "entities",
            },
        ),
        migrations.CreateModel(
            name="ReviewEntity",
            fields=[
                (
                    "review_entity_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("entity_id", models.CharField(max_length=100)),
                ("text", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=50)),
                ("start_pos", models.IntegerField()),
                ("end_pos", models.IntegerField()),
                ("processing_level", models.CharField(max_length=50)),
                ("confidence", models.FloatField()),
                ("context", models.TextField(blank=True)),
            ],
            options={
                "db_table": "review_entities",
            },
        ),
        migrations.CreateModel(
            name="ReviewTask",
            fields=[
                (
                    "review_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("original_text", models.TextField()),
                ("status", models.CharField(default="pending", max_length=20)),
                ("processing_level", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "review_tasks",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("role", models.CharField(default="user", max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Alias",
            fields=[
                ("alias_id", models.AutoField(primary_key=True, serialize=False)),
                ("alias_name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "entity_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="entity.entity"
                    ),
                ),
            ],
            options={
                "db_table": "aliases",
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                ("candidate_id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=50)),
                ("confidence", models.FloatField()),
                ("source", models.CharField(max_length=50)),
                (
                    "review_entity_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entity.reviewentity",
                    ),
                ),
            ],
            options={
                "db_table": "candidates",
            },
        ),
        migrations.CreateModel(
            name="ReviewResult",
            fields=[
                ("result_id", models.AutoField(primary_key=True, serialize=False)),
                ("entity_id", models.CharField(max_length=100)),
                ("original_text", models.CharField(max_length=255)),
                ("approved_candidate_text", models.CharField(max_length=255)),
                ("approved_candidate_label", models.CharField(max_length=50)),
                ("add_as_alias", models.BooleanField(default=False)),
                ("action", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "review_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entity.reviewtask",
                    ),
                ),
            ],
            options={
                "db_table": "review_results",
            },
        ),
        migrations.AddField(
            model_name="reviewentity",
            name="review_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="entity.reviewtask"
            ),
        ),
    ]
