# Generated by Django 5.2 on 2026-04-08 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alias",
            name="entity_id",
            field=models.ForeignKey(
                db_column="entity_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="entity.entity",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="review_entity_id",
            field=models.ForeignKey(
                db_column="review_entity_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="entity.reviewentity",
            ),
        ),
        migrations.AlterField(
            model_name="reviewentity",
            name="review_id",
            field=models.ForeignKey(
                db_column="review_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to="entity.reviewtask",
            ),
        ),
        migrations.AlterField(
            model_name="reviewresult",
            name="review_id",
            field=models.ForeignKey(
                db_column="review_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="entity.reviewtask",
            ),
        ),
    ]
