# Generated by Django 5.2 on 2026-03-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktail", "0002_llm_canonical_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmcanonicalmap",
            name="canonical_name_zh",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="name_zh",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="recipebalancefeature",
            name="flavor_dist",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="recipebalancefeature",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="recipebalancefeature",
            name="role_dist",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
