# Generated by Django 5.2 on 2026-03-29 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cocktail", "0003_recipe_name_zh_and_more"),
        ("cocktail", "0005_combo_adjust_tables"),
    ]

    operations = []
