# Generated by Django 5.2 on 2026-04-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktail", "0006_merge_20260329_1030"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientType",
            fields=[
                (
                    "ingredient_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("type_tag", models.CharField(max_length=100)),
                ("source", models.CharField(max_length=100)),
                ("confidence", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ingredient_type",
            },
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="name_zh",
            new_name="recipe_name_zh",
        ),
        migrations.RenameIndex(
            model_name="recipecomboadjustresult",
            new_name="recipe_comb_recipe__11f1c1_idx",
            old_name="cocktail_rec_recipe_id_sna_idx",
        ),
        migrations.RenameIndex(
            model_name="recipecomboadjustresult",
            new_name="recipe_comb_recipe__787f04_idx",
            old_name="cocktail_rec_recipe_id_tar_idx",
        ),
        migrations.RenameIndex(
            model_name="recipecomboadjustresult",
            new_name="recipe_comb_recipe__27d05c_idx",
            old_name="cocktail_rec_recipe_id_acc_idx",
        ),
        migrations.RenameIndex(
            model_name="recipecomboadjustresult",
            new_name="recipe_comb_rank_no_39cba1_idx",
            old_name="cocktail_rec_rank_no_idx",
        ),
        migrations.RenameIndex(
            model_name="recipecomboadjustresult",
            new_name="recipe_comb_recipe__d4cf03_idx",
            old_name="cocktail_rec_recipe_id_ran_idx",
        ),
        migrations.RenameIndex(
            model_name="recipecomboadjuststep",
            new_name="recipe_comb_plan_id_1e06b4_idx",
            old_name="cocktail_ste_plan_id_ste_idx",
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions_zh",
            field=models.TextField(null=True),
        ),
    ]
