#!/usr/bin/env python3
"""
映射字典模块

包含各种实体映射字典，如风味词映射、双语映射等
"""

# 风味词映射字典，将常见风味描述词映射到六个基本维度
FLAVOR_MAPPING = {
    # sour 相关
    "sour": "sour",
    "acidic": "sour",
    "tart": "sour",
    "tangy": "sour",
    "citrusy": "sour",
    "lemony": "sour",
    "limey": "sour",
    "vinegary": "sour",
    "酸": "sour",
    "偏酸": "sour",
    "酸一点": "sour",
    "清酸": "sour",
    "柠檬酸": "sour",
    "果酸": "sour",
    "醋酸": "sour",
    "柑橘味": "sour",
    "酸甜": "sour",
    
    # sweet 相关
    "sweet": "sweet",
    "sugary": "sweet",
    "honeyed": "sweet",
    "syrupy": "sweet",
    "fruity sweet": "sweet",
    "candy-like": "sweet",
    "dessert-like": "sweet",
    "甜": "sweet",
    "甜一点": "sweet",
    "果甜": "sweet",
    "蜜甜": "sweet",
    "甜腻": "sweet",
    "清甜": "sweet",
    
    # bitter 相关
    "bitter": "bitter",
    "sharp": "bitter",
    "astringent": "bitter",
    "hoppy": "bitter",
    "medicinal": "bitter",
    "herbal bitter": "bitter",
    "苦": "bitter",
    "苦一点": "bitter",
    "苦涩": "bitter",
    "药苦": "bitter",
    "草本苦": "bitter",
    
    # aroma 相关
    "aroma": "aroma",
    "fragrant": "aroma",
    "aromatic": "aroma",
    "smoky": "aroma",
    "woody": "aroma",
    "earthy": "aroma",
    "spicy": "aroma",
    "herbal": "aroma",
    "floral": "aroma",
    "nutty": "aroma",
    "vanilla": "aroma",
    "chocolate": "aroma",
    "coffee": "aroma",
    "caramel": "aroma",
    "toasty": "aroma",
    "burnt": "aroma",
    "smokey": "aroma",  # 常见拼写错误
    "香": "aroma",
    "香气": "aroma",
    "芳香": "aroma",
    "花香": "aroma",
    "烟熏": "aroma",
    "木质": "aroma",
    "草本": "aroma",
    "香料": "aroma",
    "坚果香": "aroma",
    "香草": "aroma",
    "巧克力香": "aroma",
    "咖啡香": "aroma",
    "焦糖香": "aroma",
    "烤香": "aroma",
    
    # fruity 相关
    "fruity": "fruity",
    "berry": "fruity",
    "apple": "fruity",
    "banana": "fruity",
    "cherry": "fruity",
    "grape": "fruity",
    "orange": "fruity",
    "peach": "fruity",
    "pear": "fruity",
    "pineapple": "fruity",
    "strawberry": "fruity",
    "watermelon": "fruity",
    "citrus": "fruity",
    "果香": "fruity",
    "水果感": "fruity",
    "浆果": "fruity",
    "柑橘": "fruity",
    "热带水果": "fruity",
    
    # body 相关
    "body": "body",
    "full-bodied": "body",
    "light-bodied": "body",
    "medium-bodied": "body",
    "heavy": "body",
    "light": "body",
    "creamy": "body",
    "rich": "body",
    "smooth": "body",
    "silky": "body",
    "watery": "body",
    "thick": "body",
    "thin": "body",
    "顺滑": "body",
    "醇厚": "body",
    "清爽": "body",
    "厚重": "body",
    "轻盈": "body",
    " creamy": "body",
    "浓郁": "body"
}

# 常见中英文映射
bilingual_mapping = {
    # 食材
    '龙舌兰': 'tequila',
    '龙舌兰酒': 'tequila',
    '墨西哥龙舌兰酒': 'tequila',
    '伏特加': 'vodka',
    '金酒': 'gin',
    '朗姆酒': 'rum',
    '威士忌': 'whiskey',
    '白兰地': 'brandy',
    '利口酒': 'liqueur',
    '青柠': 'lime',
    '柠檬': 'lemon',
    '橙子': 'orange',
    '苹果': 'apple',
    '香蕉': 'banana',
    '樱桃': 'cherry',
    '葡萄': 'grape',
    '桃子': 'peach',
    '梨': 'pear',
    '菠萝': 'pineapple',
    '草莓': 'strawberry',
    '西瓜': 'watermelon',
    '黄瓜': 'cucumber',
    '番茄': 'tomato',
    '洋葱': 'onion',
    '大蒜': 'garlic',
    '生姜': 'ginger',
    '薄荷': 'mint',
    '罗勒': 'basil',
    '百里香': 'thyme',
    '迷迭香': 'rosemary',
    '香菜': 'cilantro',
    '欧芹': 'parsley',
    
    # 风味
    '酸': 'sour',
    '偏酸': 'sour',
    '酸一点': 'sour',
    '清酸': 'sour',
    '甜': 'sweet',
    '甜一点': 'sweet',
    '果甜': 'sweet',
    '苦': 'bitter',
    '苦一点': 'bitter',
    '香': 'aroma',
    '香气': 'aroma',
    '芳香': 'aroma',
    '果香': 'fruity',
    '水果感': 'fruity',
    '花香': 'aroma',
    '烟熏': 'aroma',
    '木质': 'aroma',
    '顺滑': 'body',
    '醇厚': 'body',
    '清爽': 'body',
    
    # 角色
    '基酒': 'base spirit',
    '主料': 'base spirit',
    '辅料': 'modifier',
    '调味': 'modifier',
    '甜味剂': 'sweetener',
    '酸': 'acid',
    '苦味剂': 'bitters',
    '装饰': 'garnish',
    '稀释': 'dilution',
    '其他': 'other',
    
    # 通用名词
    '鸡尾酒': 'cocktail'
}

# 通用名词列表
COMMON_NOUNS = [
    "鸡尾酒",
    "drink",
    "beverage",
    "cocktail"
]
